modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="aster_risk"
version="1.3.0"
displayName="Aster Risk"
displayURL="https://github.com/starMaylight/aster_risk"
logoFile="logo.png"
credits="starMaylight"
authors="starMaylight"
description="Moonlight, ritual, and more! A celestial magic mod for Minecraft."

[[dependencies.aster_risk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.aster_risk]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
